### ISSUE TITLE
Understanding xgbatch

### ISSUE THREAD

**Issue by tahashmi** [ehenry2/xgbatch#2]
Hi @ehenry2 , Indeed an interesting application for Arrow Flight. I am new to xgboost, started looking into it through your project . 

I have tested `iris.xgb` model on a client-server model and it's working fine. 

For `dask` usage, Can you please provide some models to use instead of `model.model` (maybe recommend one from [here](https://github.com/dmlc/xgboost/blob/4224c08cacceba3f83f90e387c07aa6205a83bfa/tests/python/generate_models.py)) and some sample scoring input `data.csv` file for testing/understanding purpose. Thanks.

**Comment by ehenry2** [comment]
Hi there, really excited you have found this project! This project is brand new so far, so I don't have a lot of examples or documentation yet, but I added an integration test for pandas [here](https://github.com/ehenry2/xgbatch/blob/main/integration/test_clients.py#L68) that has the data in csv format so you can see what it looks like without dealing with the parquet files. If you're looking to use it with Dask, see the example [here](https://github.com/ehenry2/xgbatch/blob/main/integration/test_clients.py#L53) in the integration test. The example in the integration test uses dask to orchestrate scoring on an xgboost model trained normally (e.g. not using dask)...I haven't tested whether it works with a model trained using the dask API.  I'll add an example with a csv file in the next few days. I haven't had a change to test this with a more realistic example than the IRIS dataset, so let me know if you run into any issues!

**Comment by tahashmi** [comment]
Thanks @ehenry2 , This was very helpful.

**Comment by tahashmi** [comment]
Are you planning to compare such an implementation without Arrow Flight for both (client-server and Dask) modes? Actually I am writing a paper on benchmarking Arrow Flight for different use cases. Your work might be a very useful use case as well. So I am wondering if you are already planing to write/publish something on it or we can collaborate in my paper for this use case. Thanks.

**Comment by ehenry2** [comment]
Sorry for the late response, feel free to use this as part of your research and feel free to reach if you need help with anything. Thanks!
